#!/usr/bin/python3
import math

def isPrime(input):
	i = 3
	while (i * i <= input):
		if (input % i == 0):
			return False
		i = i + 2
	return True

def getPrimes(input):
    primeList = []
    for counter in range (1,input, 2):
        if (isPrime(counter)):
            primeList.append(counter)
    return primeList

def calcNorm(x,y,z):
    return math.sqrt((x**2)+(y**2)+(z**2))

def goldbach(primeList, input):
    norm = 0.0
    newNorm = 0.0
    goldList = []
    length = len(primeList) - 1

    for k_pos in range(length, int((length + 1 )/ 3), -1):
        k = primeList[k_pos]
        for j_pos in range(k_pos-1, 0, -1):
            j = primeList[j_pos]
            i = input - k - j
            if (isPrime(i) and i < j):
                newNorm = calcNorm(i,j,k)
                if (newNorm < norm or norm == 0.0):
                    norm = newNorm
                    goldList = [i,j,k]
    
    return goldList



#The actual program

getInput = True

while (getInput):
    numstr = input("Enter an odd number greater than 7: " )
    numInput = int(numstr)
    if (numInput > 7 or numInput % 2 != 0):
        getInput = False

primeList = getPrimes(numInput)

goldList = goldbach(primeList, numInput)

print (numInput, ":", goldList)